/*
------------------------------------------------------------------------------
WARNING:
This file is auto-generated by @nestizen/graphql-plugin.
Changes to this file will be lost if the code is regenerated.
------------------------------------------------------------------------------
*/
/* eslint-disable */

import {
  Resolver,
  Query,
  Mutation,
  ResolveField,
  Args,
  Int,
  Parent,
} from '@nestjs/graphql';
import { CategoryMetadataServiceBase } from './category-metadata.service.base';
import {
  CategoryMetadata,
  FindUniqueCategoryMetadataArgs,
  FindManyCategoryMetadataArgs,
  CreateOneCategoryMetadataArgs,
  UpdateOneCategoryMetadataArgs,
  DeleteOneCategoryMetadataArgs,
  AggregateCategoryMetadata,
  CategoryMetadataAggregateArgs,
  CategoryMetadataGroupBy,
  CategoryMetadataGroupByArgs,
  Category,
} from '../../nestizen/graphql-types';

@Resolver(() => CategoryMetadata)
export class CategoryMetadataResolverBase {
  constructor(public readonly service: CategoryMetadataServiceBase) {}

  @Query(() => CategoryMetadata, { nullable: true })
  async categoryMetadata(@Args() args: FindUniqueCategoryMetadataArgs) {
    return this.service.findUnique(args);
  }

  @Query(() => [CategoryMetadata], { nullable: false })
  async categoryMetadatas(@Args() args: FindManyCategoryMetadataArgs) {
    return this.service.findMany(args);
  }

  @Mutation(() => CategoryMetadata, { nullable: false })
  async createCategoryMetadata(@Args() args: CreateOneCategoryMetadataArgs) {
    return this.service.create(args);
  }

  @Mutation(() => CategoryMetadata, { nullable: false })
  async updateCategoryMetadata(@Args() args: UpdateOneCategoryMetadataArgs) {
    return this.service.update(args);
  }

  @Mutation(() => CategoryMetadata, { nullable: false })
  async deleteCategoryMetadata(@Args() args: DeleteOneCategoryMetadataArgs) {
    return this.service.delete(args);
  }

  @Query(() => Int, { nullable: false })
  async categoryMetadataCount(@Args() args: FindManyCategoryMetadataArgs) {
    return this.service.count(args);
  }

  @Query(() => AggregateCategoryMetadata, { nullable: false })
  async categoryMetadataAggregate(@Args() args: CategoryMetadataAggregateArgs) {
    return this.service.aggregate(args);
  }

  @Query(() => [CategoryMetadataGroupBy], { nullable: false })
  async categoryMetadataGroupBy(@Args() args: CategoryMetadataGroupByArgs) {
    return this.service.groupBy(args);
  }

  @ResolveField(() => Category)
  async category(@Parent() parent: CategoryMetadata) {
    return this.service.resolveCategory(parent);
  }
}
