/*
------------------------------------------------------------------------------
WARNING:
This file is auto-generated by @nestizen/graphql-plugin.
Changes to this file will be lost if the code is regenerated.
------------------------------------------------------------------------------
*/
/* eslint-disable */

import { Prisma, Profile } from '@prisma/client';
import { PrismaService } from '../../../prisma/prisma.service';

export class ProfileServiceBase {
  constructor(public readonly prisma: PrismaService) {}

  async findUnique(args: Prisma.ProfileFindUniqueArgs) {
    return this.prisma.client.profile.findUnique(args);
  }

  async findMany(args: Prisma.ProfileFindManyArgs) {
    return this.prisma.client.profile.findMany(args);
  }

  async create(args: Prisma.ProfileCreateArgs) {
    return this.prisma.client.profile.create(args);
  }

  async createMany(args: Prisma.ProfileCreateManyArgs) {
    return this.prisma.client.profile.createMany(args);
  }

  async update(args: Prisma.ProfileUpdateArgs) {
    return this.prisma.client.profile.update(args);
  }

  async updateMany(args: Prisma.ProfileUpdateManyArgs) {
    return this.prisma.client.profile.updateMany(args);
  }

  async delete(args: Prisma.ProfileDeleteArgs) {
    return this.prisma.client.profile.delete(args);
  }

  async deleteMany(args: Prisma.ProfileDeleteManyArgs) {
    return this.prisma.client.profile.deleteMany(args);
  }

  async count(args: Prisma.ProfileCountArgs) {
    return this.prisma.client.profile.count(args);
  }

  async aggregate(args: Prisma.ProfileAggregateArgs) {
    return this.prisma.client.profile.aggregate(args);
  }

  async resolveUser(parent: Profile) {
    return this.prisma.client.profile
      .findUniqueOrThrow({
        where: { id: parent.id },
      })
      .user();
  }
}
