// This file is generated by @nestizen/graphql-plugin. DO NOT MANUALLY EDIT!
/* eslint-disable */
import { Injectable } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../../../prisma/prisma.service';

@Injectable()
export class HiddenModelBaseService {
  constructor(protected readonly prisma: PrismaService) {}

  async aggregate(args: Prisma.HiddenModelAggregateArgs) {
    return this.prisma.client.hiddenModel.aggregate(args);
  }

  async createMany(args: Prisma.HiddenModelCreateManyArgs) {
    return this.prisma.client.hiddenModel.createMany(args);
  }

  async deleteMany(args: Prisma.HiddenModelDeleteManyArgs) {
    return this.prisma.client.hiddenModel.deleteMany(args);
  }

  async findFirst(args: Prisma.HiddenModelFindFirstArgs) {
    return this.prisma.client.hiddenModel.findFirst(args);
  }

  async findMany(args: Prisma.HiddenModelFindManyArgs) {
    return this.prisma.client.hiddenModel.findMany(args);
  }

  async findUnique(args: Prisma.HiddenModelFindUniqueArgs) {
    return this.prisma.client.hiddenModel.findUnique(args);
  }

  async groupBy(args: Prisma.HiddenModelGroupByArgs) {
    return this.prisma.client.hiddenModel.groupBy(args);
  }

  async updateMany(args: Prisma.HiddenModelUpdateManyArgs) {
    return this.prisma.client.hiddenModel.updateMany(args);
  }

  async count(args: Prisma.HiddenModelCountArgs) {
    return this.prisma.client.hiddenModel.count(args);
  }
}
