/*
------------------------------------------------------------------------------
WARNING:
This file is auto-generated by @nestizen/graphql-plugin.
Changes to this file will be lost if the code is regenerated.
------------------------------------------------------------------------------
*/
/* eslint-disable */

import { Resolver, Query, Mutation, Args, Int } from '@nestjs/graphql';
import { HiddenModelServiceBase } from './hidden-model.service.base';

@Resolver()
export class HiddenModelResolverBase {
  constructor(public readonly service: HiddenModelServiceBase) {}
}
