/*
------------------------------------------------------------------------------
WARNING:
This file is auto-generated by @nestizen/graphql-plugin.
Changes to this file will be lost if the code is regenerated.
------------------------------------------------------------------------------
*/
/* eslint-disable */

import { Prisma } from '@prisma/client';
import { PrismaService } from '../../../prisma/prisma.service';

export class MiscModelServiceBase {
  constructor(public readonly prisma: PrismaService) {}

  async findUnique(args: Prisma.MiscModelFindUniqueArgs) {
    return this.prisma.client.miscModel.findUnique(args);
  }

  async findMany(args: Prisma.MiscModelFindManyArgs) {
    return this.prisma.client.miscModel.findMany(args);
  }

  async create(args: Prisma.MiscModelCreateArgs) {
    return this.prisma.client.miscModel.create(args);
  }

  async createMany(args: Prisma.MiscModelCreateManyArgs) {
    return this.prisma.client.miscModel.createMany(args);
  }

  async update(args: Prisma.MiscModelUpdateArgs) {
    return this.prisma.client.miscModel.update(args);
  }

  async updateMany(args: Prisma.MiscModelUpdateManyArgs) {
    return this.prisma.client.miscModel.updateMany(args);
  }

  async delete(args: Prisma.MiscModelDeleteArgs) {
    return this.prisma.client.miscModel.delete(args);
  }

  async deleteMany(args: Prisma.MiscModelDeleteManyArgs) {
    return this.prisma.client.miscModel.deleteMany(args);
  }

  async count(args: Prisma.MiscModelCountArgs) {
    return this.prisma.client.miscModel.count(args);
  }

  async aggregate(args: Prisma.MiscModelAggregateArgs) {
    return this.prisma.client.miscModel.aggregate(args);
  }

  async groupBy(args: Prisma.MiscModelGroupByArgs) {
    return this.prisma.client.miscModel.groupBy(args);
  }
}
