/**
 * -----------------------------------------------------------------------------
 * WARNING:
 * This file is auto-generated by @nestizen/graphql-plugin.
 * Changes to this file will be lost if the code is regenerated.
 * -----------------------------------------------------------------------------
 */

import type { Prisma } from '@zenstackhq/runtime/models';
import { PrismaService } from '../../../prisma/prisma.service';

export class MiscModelServiceBase {
  constructor(public readonly prisma: PrismaService) {}

  async findUnique(args: Prisma.MiscModelFindUniqueArgs) {
    return this.prisma.client.miscModel.findUnique(args);
  }

  async findMany(args: Prisma.MiscModelFindManyArgs) {
    return this.prisma.client.miscModel.findMany(args);
  }

  async delete(args: Prisma.MiscModelDeleteArgs) {
    return this.prisma.client.miscModel.delete(args);
  }

  async count(args: Prisma.MiscModelCountArgs) {
    return this.prisma.client.miscModel.count(args);
  }

  async aggregate(args: Prisma.MiscModelAggregateArgs) {
    return this.prisma.client.miscModel.aggregate(args);
  }
}
