// This file is generated by @nestizen/graphql-plugin. DO NOT MANUALLY EDIT!
/* eslint-disable */
import { Injectable } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../../../prisma/prisma.service';

@Injectable()
export class MiscModelBaseService {
  constructor(protected readonly prisma: PrismaService) {}

  async aggregate(args: Prisma.MiscModelAggregateArgs) {
    return this.prisma.client.miscModel.aggregate(args);
  }

  async createMany(args: Prisma.MiscModelCreateManyArgs) {
    return this.prisma.client.miscModel.createMany(args);
  }

  async deleteMany(args: Prisma.MiscModelDeleteManyArgs) {
    return this.prisma.client.miscModel.deleteMany(args);
  }

  async findFirst(args: Prisma.MiscModelFindFirstArgs) {
    return this.prisma.client.miscModel.findFirst(args);
  }

  async findMany(args: Prisma.MiscModelFindManyArgs) {
    return this.prisma.client.miscModel.findMany(args);
  }

  async findUnique(args: Prisma.MiscModelFindUniqueArgs) {
    return this.prisma.client.miscModel.findUnique(args);
  }

  async groupBy(args: Prisma.MiscModelGroupByArgs) {
    return this.prisma.client.miscModel.groupBy(args);
  }

  async updateMany(args: Prisma.MiscModelUpdateManyArgs) {
    return this.prisma.client.miscModel.updateMany(args);
  }

  async count(args: Prisma.MiscModelCountArgs) {
    return this.prisma.client.miscModel.count(args);
  }
}
