/*
------------------------------------------------------------------------------
WARNING:
This file is auto-generated by @nestizen/graphql-plugin.
Changes to this file will be lost if the code is regenerated.
------------------------------------------------------------------------------
*/
/* eslint-disable */

import {
  Resolver,
  Query,
  Mutation,
  Args,
  Int,
  Parent,
  ResolveField,
} from '@nestjs/graphql';
import { TagServiceBase } from './tag.service.base';
import {
  Tag,
  FindUniqueTagArgs,
  FindManyTagArgs,
  CreateOneTagArgs,
  UpdateOneTagArgs,
  DeleteOneTagArgs,
  AggregateTag,
  TagAggregateArgs,
  TagGroupBy,
  TagGroupByArgs,
  FindManyUserArgs,
  User,
} from '../../nestizen/graphql-types';

@Resolver(() => Tag)
export class TagResolverBase {
  constructor(public readonly service: TagServiceBase) {}

  @Query(() => Tag, { nullable: true })
  async tag(@Args() args: FindUniqueTagArgs) {
    return this.service.findUnique(args);
  }

  @Query(() => [Tag], { nullable: false })
  async tags(@Args() args: FindManyTagArgs) {
    return this.service.findMany(args);
  }

  @Mutation(() => Tag, { nullable: false })
  async createTag(@Args() args: CreateOneTagArgs) {
    return this.service.create(args);
  }

  @Mutation(() => Tag, { nullable: false })
  async updateTag(@Args() args: UpdateOneTagArgs) {
    return this.service.update(args);
  }

  @Mutation(() => Tag, { nullable: false })
  async deleteTag(@Args() args: DeleteOneTagArgs) {
    return this.service.delete(args);
  }

  @Query(() => Int, { nullable: false })
  async tagCount(@Args() args: FindManyTagArgs) {
    return this.service.count(args);
  }

  @Query(() => AggregateTag, { nullable: false })
  async tagAggregate(@Args() args: TagAggregateArgs) {
    return this.service.aggregate(args);
  }

  @Query(() => [TagGroupBy], { nullable: false })
  async tagGroupBy(@Args() args: TagGroupByArgs) {
    return this.service.groupBy(args);
  }

  @ResolveField(() => [User], { nullable: false })
  async users(@Parent() parent: Tag, @Args() args: FindManyUserArgs) {
    return this.service.resolveUsers(parent, args);
  }
}
